<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BPM.Domain\BPM.Domain.csproj" />
    <ProjectReference Include="..\BPM.Application\BPM.Application.csproj" />
    <ProjectReference Include="..\BPM.Infrastructure\BPM.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
